// <auto-generated />
using System;
using Group6Flight.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Group6Flight.Migrations
{
    [DbContext(typeof(FlightDbContext))]
    [Migration("20260414170028_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("Group6Flight.Models.Airline", b =>
                {
                    b.Property<int>("AirlineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AirlineId");

                    b.ToTable("Airline");

                    b.HasData(
                        new
                        {
                            AirlineId = 1,
                            ImageName = "american_airlines.png",
                            Name = "American Airlines"
                        },
                        new
                        {
                            AirlineId = 2,
                            ImageName = "delta_air_lines.png",
                            Name = "Delta Air Lines"
                        },
                        new
                        {
                            AirlineId = 3,
                            ImageName = "united_airlines.png",
                            Name = "United Airlines"
                        },
                        new
                        {
                            AirlineId = 4,
                            ImageName = "southwest_airlines.png",
                            Name = "Southwest Airlines"
                        },
                        new
                        {
                            AirlineId = 5,
                            ImageName = "alaska_airlines.png",
                            Name = "Alaska Airlines"
                        },
                        new
                        {
                            AirlineId = 6,
                            ImageName = "jetblue_airways.png",
                            Name = "JetBlue Airways"
                        });
                });

            modelBuilder.Entity("Group6Flight.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AircraftType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AirlineId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("CabinType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("Emission")
                        .HasColumnType("REAL");

                    b.Property<string>("FlightCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("FlightId");

                    b.HasIndex("AirlineId");

                    b.ToTable("Flight");

                    b.HasData(
                        new
                        {
                            FlightId = 1,
                            AircraftType = "Boeing 737",
                            AirlineId = 1,
                            ArrivalTime = new TimeSpan(0, 11, 45, 0, 0),
                            CabinType = "Economy",
                            Date = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 8, 30, 0, 0),
                            Emission = 250.5,
                            FlightCode = "AA101",
                            From = "New York",
                            Price = 320.00m,
                            To = "Los Angeles"
                        },
                        new
                        {
                            FlightId = 2,
                            AircraftType = "Airbus A320",
                            AirlineId = 2,
                            ArrivalTime = new TimeSpan(0, 16, 10, 0, 0),
                            CabinType = "Business",
                            Date = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 14, 15, 0, 0),
                            Emission = 180.19999999999999,
                            FlightCode = "DL202",
                            From = "Atlanta",
                            Price = 450.00m,
                            To = "Chicago"
                        },
                        new
                        {
                            FlightId = 3,
                            AircraftType = "Boeing 757",
                            AirlineId = 3,
                            ArrivalTime = new TimeSpan(0, 11, 0, 0, 0),
                            CabinType = "Economy",
                            Date = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 9, 0, 0, 0),
                            Emission = 120.0,
                            FlightCode = "UA303",
                            From = "San Francisco",
                            Price = 210.00m,
                            To = "Seattle"
                        },
                        new
                        {
                            FlightId = 4,
                            AircraftType = "Boeing 737",
                            AirlineId = 4,
                            ArrivalTime = new TimeSpan(0, 8, 30, 0, 0),
                            CabinType = "Economy",
                            Date = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 6, 45, 0, 0),
                            Emission = 140.69999999999999,
                            FlightCode = "SW404",
                            From = "Dallas",
                            Price = 180.00m,
                            To = "Denver"
                        },
                        new
                        {
                            FlightId = 5,
                            AircraftType = "Boeing 777",
                            AirlineId = 5,
                            ArrivalTime = new TimeSpan(0, 10, 0, 0, 0),
                            CabinType = "First Class",
                            Date = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 22, 0, 0, 0),
                            Emission = 500.0,
                            FlightCode = "BA505",
                            From = "Boston",
                            Price = 1200.00m,
                            To = "London"
                        });
                });

            modelBuilder.Entity("Group6Flight.Models.FlightBooking", b =>
                {
                    b.Property<int>("FlightBookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FlightBookingId");

                    b.HasIndex("FlightId");

                    b.ToTable("FlightBookings");
                });

            modelBuilder.Entity("Group6Flight.Models.Flight", b =>
                {
                    b.HasOne("Group6Flight.Models.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("Group6Flight.Models.FlightBooking", b =>
                {
                    b.HasOne("Group6Flight.Models.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });
#pragma warning restore 612, 618
        }
    }
}
